# Generated by Django 4.0.2 on 2022-03-04 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concurso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concurso',
            name='categoria',
            field=models.IntegerField(choices=[[0, '---'], [1, 'Desayunos'], [2, 'Almuerzos'], [3, 'Cenas'], [4, 'Snacks']]),
        ),
        migrations.AlterField(
            model_name='receta',
            name='categoria',
            field=models.IntegerField(choices=[[0, '---'], [1, 'Desayunos'], [2, 'Almuerzos'], [3, 'Cenas'], [4, 'Snacks']]),
        ),
    ]
